import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import SideNav from "./components/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header></Header>
        <div className="md:container mx-auto px-2 md:px-10 mb-20">
          <div className="flex gap-4">
            <div className="w-full">
              {children}
            </div>
            <div className="hidden md:block w-[20%]">
              <SideNav setMenuOpen={undefined}></SideNav>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
